### ISSUE TITLE
[Bug]: royal mail xp 

### ISSUE THREAD

**Issue by strawberryboatowner** [armastudiosuk/issue-tracker#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when doing the royal mail job, my xp level is 0 with -99000 xp, this happened when i was level 99 trying to reach level 100 however my xp level went into the minus. 

### Expected behaviour

?

### Steps to reproduce

?

### Any Texture Packs? (If so list)

reshade

### ARMA User ID

1621

**Comment by kwt** [comment]
Resolved as June 29th
