### ISSUE TITLE
[Bug]:Police Weapons // inventory clock off

### ISSUE THREAD

**Issue by tiktokenjoyer** [armastudiosuk/issue-tracker#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If you are a police officer and have all weapons in inventory stored, and you clock off it doesn't check your inventory, e.g. seize it.

### Expected behaviour

I went to the event "organ heist" after finished had the weapons "in inventory not equipped" went to pd to clock off. 
Proceeded to clock off, and the weapons wasn't taken from my inventory.

i believe it only checks "equipped items" > seizes if clocked off. | and not if its in inventory.

### Steps to reproduce

1. be clocked on as pd.
2. have weapons in inventory (non equipped)
3. Clock off 
4. Weapons (wont be seized)

### Any Texture Packs? (If so list)

no

### ARMA User ID

3476

**Comment by kwt** [comment]
This isn't an issue as you cannot equip those weapons whilst not clocked on.
