### ISSUE TITLE
[Bug]:  DJmenu not working correctly

### ISSUE THREAD

**Issue by Stubixcube** [armastudiosuk/issue-tracker#14]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

djmenu:  music doesn't play/stop when it's supposed to

### Expected behaviour

Music should stop/start when choosing the command 

### Steps to reproduce

1: type /djmenu
2: type /play "=xxxxxxxxxx" from youtube then hit enter
3: type /djmenu again select stop music or end session

### Any Texture Packs? (If so list)

none

### ARMA User ID

7986

**Comment by kwt** [comment]
Should be fixed as of next restart.
