### ISSUE TITLE
[Bug]: dj liscence

### ISSUE THREAD

**Issue by yellty12** [armastudiosuk/issue-tracker#2]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when using dj liscence no music plays even if inputting correctly

### Expected behaviour

should play music but no music plays

### Steps to reproduce

1. spawn dj board
2. /play and then whatever yt video id
3. no music comes out

### Any Texture Packs? (If so list)

no

### ARMA User ID

1839

**Comment by kwt** [comment]
Unable to reproduce issue. If issue persists please provide a video so it can be properly replicated.
