### ISSUE TITLE
[Bug]: Discord Bot

### ISSUE THREAD

**Issue by tiktokenjoyer** [armastudiosuk/issue-tracker#3]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![image](https://github.com/armastudiosuk/issue-tracker/assets/102319182/8ad3fa7f-62cb-46c0-932f-a965d86f8ad2)

!getroles is not a supported command within the channel of #Tag-request it will redirect you to -> #Bot-Commands.

### Expected behaviour

Need to add a exception or just need to add command for that channel, i guess idk.

### Steps to reproduce

Go to Tag-request
Type !getroles
Press enter.

### Any Texture Packs? (If so list)

no

### ARMA User ID

3476

**Comment by kwt** [comment]
Use #bot-commands simple.
