### ISSUE TITLE
[Bug]: greenzones block car leaveage

### ISSUE THREAD

**Issue by randomahhhname** [armastudiosuk/issue-tracker#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i try to leave a greenzone in a spicey whip, i get stuck in mid air.

### Expected behaviour

get slapped in the face by an invisible barrier

### Steps to reproduce

get a whip
drive out greenzone
get shit on

### Any Texture Packs? (If so list)

NVE, Reshade

### ARMA User ID

2008

**Comment by kwt** [comment]
Thanks for the Report
I can now confirm this has been fixed
