### ISSUE TITLE
[Bug]:  PD armoury permissions

### ISSUE THREAD

**Issue by T0mmytom123** [armastudiosuk/issue-tracker#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Im AFO in pd and my ar is M1A4 or whatever it caleld but doesnt let me get it out says 'You do not have required permissions for this weapon' and i do have large arms role in pd discord 
![arma pd armoury bug](https://github.com/armastudiosuk/issue-tracker/assets/126427854/5d5ecf97-aec1-464f-b8a1-2906c5630b35)

### Expected behaviour

unable to get right weapons

### Steps to reproduce

n/a

### Any Texture Packs? (If so list)

no

### ARMA User ID

6445

**Comment by kwt** [comment]
Can you provide a video as it seems I'm unable to recreate this issue. The only time that notify appears is when you attempt to get a sniper from the armoury without the sniper trained role. It detects for sniper models specifically with w_sr, the M4 being an ar has the model prefix w_ar

**Comment by kwt** [comment]
This issue should be resolved for tomorrow's 10am restart.

**Comment by T0mmytom123** [comment]
https://medal.tv/games/gta-v/clips/1KSFhyvR31c_Gt/d1337lyyJ4Vt?invite=cr-MSxSZkosMTk5NzMwODQs
